name: Build and Test

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Eventrian.sln

      - name: Build
        run: dotnet build Eventrian.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Eventrian.sln --no-build --configuration Release